<?xml version="1.0"?>
<package format="3">
  <name>diagnostic_common_diagnostics</name>
  <version>1.11.0</version>
  <description>diagnostic_common_diagnostics</description>
  <author email="brice.rebsamen@gmail.com">Brice Rebsamen</author>
  <maintainer email="guglielmo.gemignani@gmail.com">Guglielmo Gemignani</maintainer>
  <maintainer email="namniart@gmail.com">Austin Hendrix</maintainer>

  <license>BSD</license>

  <url type="website">http://ros.org/wiki/diagnostic_common_diagnostics</url>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>rospy</build_depend>
  <build_depend>diagnostic_updater</build_depend>
  <build_depend>rostest</build_depend>

  <exec_depend>diagnostic_updater</exec_depend>
  <exec_depend>hddtemp</exec_depend>
  <exec_depend>lm-sensors</exec_depend>
  <exec_depend>rospy</exec_depend>
  <exec_depend>tf</exec_depend>
  <exec_depend condition="$ROS_PYTHON_VERSION == 2">python-psutil</exec_depend>
  <exec_depend condition="$ROS_PYTHON_VERSION == 3">python3-psutil</exec_depend>

  <export>
    <architecture_independent/>
  </export>
</package>
